(define (sq x)
  (* x x))
(define (cube x)
  (* x x x))
(define (abs x)
  (if (< x 0)
    (- x)
    x))
(define (good-enough guess x)
  (< (abs (- x (cube guess))) 0.0001))
(define (improve guess x)
  (- guess (/ (- (cube guess) 3) (* 3 (sq x)))))
(define (cubeiter guess x) 
  (if (good-enough guess x) 
    guess 
  (cubeiter (improve guess x))))
(define (cubert x) (cubeiter 1.0 x))

(cubert 27)
